In [2]:
list = [1,2,3,4,5,6]
print(list)


import numpy as np
array = np.array([2,3,4,5,6,7])
print(array)

[1, 2, 3, 4, 5, 6]
[2 3 4 5 6 7]


In [3]:
# 1d arrat  --- one dimensional array

# import numpy as np

ar_id = np.array([10,33,44,55,66,77])

print(ar_id)

[10 33 44 55 66 77]


In [5]:
# 2d array

ar_2d = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

print(ar_2d)
                 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# Multi Dimensional aary
# Matrix

matrix = np.array([[2,4,6],
                  [8,10,12]])

print(matrix)

[[ 2  4  6]
 [ 8 10 12]]


In [16]:
arr = np.array([1,2,3,4,5,6])

print("array:" , arr)


list = [3,4,5,6,7,8,9]

ar_list = np.array(list)
print("list in array: ", ar_list)


list2 = [63,64,54,64,74,48,59]
print("list: ", list2)

array: [1 2 3 4 5 6]
list in array:  [3 4 5 6 7 8 9]
list:  [63, 64, 54, 64, 74, 48, 59]


In [22]:
# with default values

zeros_array = np.zeros(4)

print(zeros_array)
print(zeros_array.shape)   # for shape o/p is 4

[0. 0. 0. 0.]
(4,)


In [24]:
# once(shape)
 # ones array and its shape
one_array=np.ones((2,3))
print(one_array)
print(one_array.shape)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)


In [26]:
one_array=np.ones((4,4))  # ones array and its shape
print(one_array)
print(one_array.shape)


one_array=np.ones((3,2))  # ones array and its shape
print(one_array)
print(one_array.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(4, 4)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
(3, 2)


In [27]:
# full(shape, value)

filled_array = np.full((2,2),7)
print(filled_array)

[[7 7]
 [7 7]]


In [35]:
full_array = np.full((3,4),2) # 2 is value for out put in array it can be change or replace any value and that is print

print(full_array)

print("shape of this array: ",full_array.shape)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
shape of this array:  (3, 4)


In [53]:
# creating sequences of numbers in numpy
#arange()
#arange(start , stop , step)

seq_array = np.arange(1,10,2)
print(seq_array)

print("shape of this sequence array:",seq_array.shape)

[1 3 5 7 9]
shape of this sequence array: (5,)


In [58]:
seq2_array = np.arange(10, 100, 5)
print(seq2_array)
print("shape of this seq2 :", seq2_array.shape)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
shape of this seq2 : (18,)


In [63]:
# crating a identity matrix
# its a sequre matrix
#eye(size)

id_matrix = np.eye(3)
print(id_matrix)

print(id_matrix.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)


In [62]:
id2_mat = np.eye(5)
print(id2_mat)

print(id2_mat.shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
(5, 5)


# Chapter-2 Array Properties and Operations

In [82]:
# array --> properties --> oprations
# Numpy properties
# find --> shape, size, type
# attribute -- shape

arr_2d = np.array([[1,2,3],
                   [4,5,6]])
print(arr_2d.shape)

print(arr_2d.ndim)



(2, 3)
2


In [80]:
# total number of element in array size

arr = np.array([[10,20,30],[40,50,60]])
print(arr.size)

print(arr.shape)

print(arr_3d.ndim)

6
(2, 3)
3


In [87]:
#ndim  >> number of dimensions

#arr.ndim

arr_1d = np.array([1,2,3])
arr_2d = np.array([[1,2,3], [4,5,6]])
arr_3d = np.array([[[1,2],[3,4],[5,6],[7,8]]])

print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)


1
2
3


In [91]:
arr = np.array([10,20,30,40])

print(arr.dtype)

int64


In [98]:
# astype

arr = np.array([1.2, 3.5, 6.8])
print(arr.dtype)

int_arr =  arr.astype(int)
print(int_arr)

print(int_arr.dtype)
print(int_arr.shape)

float64
[1 3 6]
int64
(3,)


In [103]:
# maths


arr = np.array([10,20,30])

print(arr + 5)
print(arr * 5)
print(arr ** 5)

[15 25 35]
[ 50 100 150]
[  100000  3200000 24300000]


In [109]:
# aggregatipn function (means Summarise data)
   
arr = np.array([10,20,30,40,50,60])

print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
print(np.std(arr))
print(np.var(arr))

210
35.0
10
60
17.07825127659933
291.6666666666667


In [111]:
#ndexing and slicing

# indexing --> with the help of idexing handle specific element(single element)

# slicing --> multiple element handle

# Fancy indeexing

# bolean masking

In [117]:
"""
array[index] # 1d array
array[row, column] # 2d
"""
#arr = ([1,3,4,5,6])
arr = np.array([10,20,30,40,50])
print(arr[0]) # first element , 0 based indexing , -1 last element
print(arr[2])  
print(arr[-1]) # last element

10
30
50


In [128]:
#slicing

"""
array[start:stop:step]

use indexing number for slicing

start
stop  : if stop indexing 3 so provide 4 value (n-1)
step


arr[start:end]   # start to end-1

negative step -1 recerse
"""

arr = np.array([10,20,30,40,50,60])

print(arr[1:5]) # index 1  to 4  # stop (n-1)
print(arr[:4]) # INDEX 0 TO 3
print(arr[::2]) # every secound element

print(arr[::-1]) # reverse elememnt



[20 30 40 50]
[10 20 30 40]
[10 30 50]
[60 50 40 30 20 10]


In [130]:
# fancy indexing  -- selecting multiple element at once
arr = np.array([10,20,30,40,50,60])

print(arr[[0,2,4]])



[10 30 50]


In [139]:
# boolen masking --> conditon base > True / False

arr = np.array([10,20,30,40,50,60])

print(arr[arr > 40])



[50 60]


In [151]:
# Reshiping and manipulating arrays --> means change dimension without  data change

"""
reshape (row, column) specify new shape

when reshape if dimension match
"""
# reshape not create copy its affect orignal array view

arr = np.array([1,2,3,4,5,6])

reshaped_Arr = arr.reshape(3,2)
print(reshaped_Arr)


[[1 2]
 [3 4]
 [5 6]]


In [163]:
# flattening array --> rawll(), flatten()

# Multi Demination array conver to 1D

"""
.revel()    --> view
.flatten()  --> copy
"""
arr_2d = np.array([[1,2,3],[4,5,6]])

print(arr_2d.ravel())
print(arr_2d.flatten())



[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [160]:
arr_2d = np.array([[1,2,3],[4,5,6]])

print(arr_2d.ravel())
print(arr_2d.flatten())


[1 2 3 4 5 6]
[1 2 3 4 5 6]


# chapter 4 :Reshaping and manipulating arrays

1. add
2. remove
3. split
4. stack

In [170]:
# np.inser(array, index, value, axis=None)  --> pass the indexing number
# array - orignal array
# index - 
# value
# axis
# axis = 0, means row wise data insert
# axis =1 , means column wise data insert


arr = np.array([10,20,30,40, 50, 60])
print(arr)
new_arr = np.insert(arr, 2, 100 , axis=0)

print(new_arr)

[10 20 30 40 50 60]
[ 10  20 100  30  40  50  60]


In [180]:
arr_2d = np.array([[1,2],[3,4]])
print("2d",arr_2d)
# insert new row at index 1

new_arr_2d = np.insert(arr_2d, 1, [5,6], axis=0)
print("new \n",new_arr_2d)

2d [[1 2]
 [3 4]]
new 
 [[1 2]
 [5 6]
 [3 4]]


In [183]:
# append
arr = np.array([10,20,30])
new_arr = np.append(arr, [40,50,60])
print(new_arr)


[10 20 30 40 50 60]


In [187]:
"""
np.concatenate((array1, array2), axis=0)

axis = 0 --> vertical stacking

axis = 1 --> horizontal stacking

"""

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

new_arr = np.concatenate((arr1, arr2))

print(new_arr)

[1 2 3 4 5 6]


In [189]:
# Removing Element Array
"""
np.delete(array, index, axis = none)
flattern array 

"""

arr = np.array([10,20,30,40,50,60])
print(arr)
new_arr = np.delete(arr, 0)

print(new_arr)

[10 20 30 40 50 60]
[20 30 40 50 60]


In [198]:

arr_2d = np.array([[1,2,3],[4,5,7]])

new_arr_2d = np.delete(arr_2d, 0, axis=0)

print(new_arr_2d)

[[4 5 7]]


In [199]:
# Stacking 

"""
vertically
horizontally

vstack() --> rwo wise
hstack()--> column wise
"""


arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

print(np.vstack((arr1, arr2))) # vertical stack

print(np.hstack((arr1, arr2))) # horizontal stack 

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [203]:
# spliting

"""
np.split()  # for equal part split

np.hsplit()
np.vsplit()
"""

arr = np.array([10,20,30,40,50,60])
print(np.split(arr,2))



[array([10, 20, 30]), array([40, 50, 60])]


# Chapter 5

# Brodcasting & Vectorization

In [10]:
# problem with loops Solution is Broadcasting


prices = [100,200,300]

discount = 10 #  10% discount

final_prices =[]

for price in prices:
    final_price = price - (price * discount/100)
    final_prices.append(final_price)
    
print(final_prices)

[90.0, 180.0, 270.0]


In [17]:
# Broadcating
prices = np.array([100,200,300])

discount =  10     # scaler single value
final_prices = prices - (prices * discount/100)

print(final_prices)




[ 90. 180. 270.]


In [16]:
import numpy as np

prices = np.array([100, 200, 300])
discount = 10  # scalar value (10%)

final_prices = prices - (prices * discount / 100)

print(final_prices)


[ 90. 180. 270.]


# How Numpy Handle arrays of differnt shapes

1. mateching dimenstion

2. expanding single element

3. incompatible shapes

   

In [21]:
arr = np.array([100,200,300])
result = arr * 2

print(result)

[200 400 600]


In [26]:
matrix = np.array([[1,2,3],[4,5,6]]) 

vector = np.array([10,20,30])

result = matrix  vector

print(result)

[[0 0 0]
 [0 0 0]]


In [29]:
arr1 = np.array([[1,2,3],[4,5,6]])

arr2 = np.array([1,2]
result = arr1 + arr2

print(result)


SyntaxError: '(' was never closed (3480931744.py, line 3)

In [30]:
#vectorization
list1 = [1,2,3]

list2 = [4,5,6]

result = [ x+y for x,y in zip (list1, list2)]

print(result)


[5, 7, 9]


In [34]:
#vectorization

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = arr1 + arr2

print(result)

[5 7 9]


In [35]:
arr = np.array([10,20,30])

multiplied = arr * 3

print(multiplied)

[30 60 90]


In [37]:
# Summary on BroadCasting and Vectorization

# Broadcating --> expand small array to large array for matches, fater than loops
# use convert 1D to 2D


# vectorization --> Entire array --applied oprations, 100x faster than loops
# use Matrix oprations




# Chapter: 6
# Handling Missing & Special Values



In [38]:
# why learn: suppose  you fill form

# Builtin function
# np.isnan()  --> detect  missing values
# np.nan_to_nan()

# np.isinf() -->

# Note --> nan = Not a number



In [45]:
# np.isnan(array)

arr = np.array([1,2, np.nan, 4, np.nan, 6])

print(np.isnan(arr))

print(np.nan == np.nan)

[False False  True False  True False]
False


In [50]:
# nan to num
# np.nan_to_num(array , nan=value)     Note: default = 0

arr = np.array([1,2, np.nan, 4, np.nan, 6])

cleaned_arr = np.nan_to_num(arr, nan=100)
print(cleaned_arr)



[  1.   2. 100.   4. 100.   6.]


In [52]:
# np.isinf()

arr =np.array([1,2,np.inf,4, -np.inf, 6])

print(np.isinf(arr))


# replaced

cleaned_arr = np.nan_to_num(arr, posinf=100, neginf=-1000)

print(cleaned_arr)

[False False  True False  True False]
[    1.     2.   100.     4. -1000.     6.]
